# Generated by Django 3.2.25 on 2025-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bloodstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodstock',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='bloodstock',
            constraint=models.UniqueConstraint(fields=('bloodbank', 'blood_group'), name='unique_bloodbank_blood_group'),
        ),
    ]
