# Generated by Django 3.2.25 on 2025-04-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bloodstock_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bloodstock',
            name='unique_bloodbank_blood_group',
        ),
    ]
